# -*- utf-8 -*-
import  unittest
from Test.testCase.testcase import Test_Object
from HTMLTestRunner import  HTMLTestRunner


if __name__ == '__main__':

    suite = unittest.TestSuite()
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(Test_Object))

    with open('HTMLReport.html','w') as f:
        # runner=unittest.TextTestRunner(verbosity=2)
        # runner.run(suite)
        runer = HTMLTestRunner(
                                stream=f,
                                title='test object Test Report',
                                description='generated by HTMLTestRunner.',
                                verbosity=2
                                )
        runer.run(suite)